# Changes here will be overwritten by Copier
_commit: 5b672a1
_src_path: gh:dalito/linkml-project-copier
add_example: true
copyright_year: '2025'
email: MAM@lbl.gov
full_name: Mark Miller
gh_action_docs_preview: true
gh_action_pypi: true
github_org: turbomam
license: MIT
project_description: AI-assisted automation for Critical Mineral Metabolism data curation
project_name: cmm-ai-automation
project_slug: cmm_ai_automation
