# Configuration for https://github.com/adrienverge/yamllint

extends: default

ignore: |
  docs/schema/
  .venv/
  .github/

rules:
  document-start: disable  # Don't check if document has a start marker (---).
  line-length:
    max: 80
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  new-lines: disable  # Don't check for type of new line characters.
  truthy:
    allowed-values: ['true', 'false', 'on']  # Allow 'on' for GitHub Actions
    check-keys: false
